// <auto-generated />
namespace TrainGainV1.DataContexts.ApplicationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Date));
        
        string IMigrationMetadata.Id
        {
            get { return "201504131455452_Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
