// <auto-generated />
namespace TrainGainV1.DataContexts.ApplicationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Step : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Step));
        
        string IMigrationMetadata.Id
        {
            get { return "201504020701243_Step"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
